replicaCount: 2
image:
  repository: <your-acr>.azurecr.io/sample-app
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: sample.yourdomain.com
      paths:
        - /
tls:
  - secretName: tls-secret
    hosts:
      - sample.yourdomain.com